### ISSUE TITLE
super tabs

### ISSUE THREAD

**Issue by JuniorFlorentino** [JuniorFlorentino/duvidas#1]
@ihadeed Are there any events other than tabChange?

because whenever I scroll the page, it happens to run the TabChange event, I would like it to run only when the page actually changes

[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by ihadeed** [comment]
@JuniorFlorentino 

Check the event detail object. It contains two properties: `changed` and `index`. You can check if `changed` is set to `true`.

**Comment by JuniorFlorentino** [comment]
I was able to correct it this way, because whenever I touched the super tab, the change would be triggered, even if the tab was not changed, so I am checking if the indece is different from the current one, otherwise it is because it did not change the tab

 onTabChange(ev: any) {
   switch (ev.detail.index) {
      case 0:
        if (this.tab != ev.detail.index) {
            this.listRel('receber');
             this.tab = ev.detail.index;
        }
        break;
    }
  }

**Comment by JuniorFlorentino** [comment]
this documentation link helped a lot 
https://zyra.github.io/ionic-super-tabs/configuration/
